create table if not exists clienti (
  id bigint generated by default as identity primary key,
  code text unique,
  name text not null,
  city text,
  province text,
  region text,
  country text,
  agent text,
  email text,
  phone text,
  created_at timestamptz default now()
);

create table if not exists fatture (
  id text primary key,
  date date,
  number text,
  customer_code text,
  customer_name text,
  city text,
  province text,
  agent text,
  total numeric default 0,
  created_at timestamptz default now()
);

create table if not exists righe_fattura (
  id bigint generated by default as identity primary key,
  invoice_id text references fatture(id) on delete cascade,
  code text,
  description text,
  qty numeric default 0,
  price numeric default 0,
  total numeric default 0
);

create table if not exists visite (
  id uuid primary key default gen_random_uuid(),
  date date not null,
  customer_code text,
  customer_name text,
  agent text,
  outcome text,
  next_date date,
  notes text,
  created_at timestamptz default now()
);

alter table clienti enable row level security;
alter table fatture enable row level security;
alter table righe_fattura enable row level security;
alter table visite enable row level security;

-- Versione MVP: consente lettura/scrittura con anon key. Prima di usare dati sensibili online, aggiungeremo login e policy per ruolo admin/agente.
do $$ begin
  create policy "mvp clienti all" on clienti for all using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "mvp fatture all" on fatture for all using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "mvp righe all" on righe_fattura for all using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "mvp visite all" on visite for all using (true) with check (true);
exception when duplicate_object then null; end $$;
